server:
  port: 9002

spring:
  application:
    name: Scheduler Service

  datasource:
    url: jdbc:mysql://localhost:3306/schedules?serverTimezone=UTC
    username: root
    password: 12345

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: false
    hibernate:
      ddl-auto: update
    show-sql: true

  cache:
    type: redis
    redis:
      time-to-live: 60000

  redis:
    host: localhost
    port: 6379

springdoc:
  swagger-ui:
    enabled: true
    tagsSorter: alpha
    doc-expansion: none

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
